#!/bin/zsh

file=$(fd --glob "sol.cpp" problems -x stat -c "%Y.%09X %n" | sort -rn | head -1 | cut -d" " -f2)

if [[ ! -f "$file" ]]; then
    echo "no solution file found"
    exit 1
fi

echo "── Running: $file ──"
make run F="$file"
