[Appearance]
color_scheme_path=/home/metin/.config/qt6ct/colors/catppuccin-mocha-mauve.conf
custom_palette=true
icon_theme=Papirus-Dark
standard_dialogs=default
style=Fusion

[Fonts]
fixed="MonoLisa,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,Regular,0,0"
general="Sans Serif,9,-1,5,400,0,0,0,0,0,0,0,0,0,0,1,,0,0"
