[Appearance]
color_scheme_path=/home/metin/.config/qt6ct/colors/catppuccin-mocha-lavender.conf
custom_palette=true
icon_theme=Papirus-Dark
standard_dialogs=default
style=Fusion

[Fonts]
fixed="MonoLisaCode,15,-1,5,450,0,0,0,0,0,0,0,0,0,0,1,,0,0"
general="MonoLisaText,10,-1,5,450,0,0,0,0,0,0,0,0,0,0,1,,0,0"

[Interface]
menus_have_icons=true
show_shortcuts_in_context_menus=true
stylesheets=/usr/share/qt6ct/qss/fusion-fixes.qss
toolbutton_style=2

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\x2\xcb\0\0\x3\x15\0\0\0\0\0\0\0\0\0\0\x2\xcb\0\0\x3\x15\0\0\0\0\x2\0\0\0\v@\0\0\0\0\0\0\0\0\0\0\x2\xcb\0\0\x3\x15)
