If:
  PathMatch: .*\.(c|h)
CompileFlags:
  Add:
    - -std=c23
    - -Wall
    - -Wextra
    - -Werror
    - -pedantic
    - -g
    - -O0
    - -fsanitize=address,undefined
    - -fno-omit-frame-pointer
---
If:
  PathMatch: .*\.(cpp|cc|cxx|hpp)
CompileFlags:
  Add:
    - -std=c++23
    - -Wall
    - -Wextra
    - -Wpedantic
    - -Wshadow
    - -Wconversion
    - -Wsign-conversion
    - -Wnull-dereference
    - -Wdouble-promotion
    - -Werror=return-type
    - -g
    - -fsanitize=address,undefined
    - -fno-omit-frame-pointer
    - -O1
