legacy_layout=false
horizontal=false

fps
frametime
frame_timing
throttling_status

gpu_stats
gpu_temp
gpu_core_clock
gpu_power
gpu_load_change
gpu_name

cpu_stats
cpu_temp
cpu_mhz
cpu_load_change

vram
ram

gamemode
vulkan_driver
wine
engine_version

position=top-left
font_size=20
background_alpha=0.35
round_corners=8
table_columns=3

toggle_hud=Shift_L+F10
