source = $HOME/.config/hypr/mocha.conf
# source = $HOME/.config/hypr/rose-pine.conf
# source = $HOME/.config/hypr/rose-pine.conf

# catppuccin
$accent = $mauve
$accentAlpha = $mauveAlpha

# $accent = $iris
# $accentAlpha = $irisAlpha
$font = MonoLisaText

# GENERAL
general {
  disable_loading_bar = true
  ignore_empty_input = true
  hide_cursor = true
  grace = 3
}

# wallpaper
background {
  monitor =
  path = $HOME/.config/wallpapers/mtfuji.png
  blur_passes = 0
  color = $base
}


# TIME
label {
  monitor = DP-3
  text = $TIME12
  color = $text
  font_size = 90
  font_family = $font
  position = 0, -150
  halign = center
  valign = top
}

# DATE
label {
  monitor = DP-3
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $text
  font_size = 25
  font_family = $font
  position = 0, -300
  halign = center
  valign = top
}

# INPUT FIELD
input-field {
  monitor = DP-3
  size = 300, 60
  outline_thickness = 4
  dots_size = 0.2
  dots_spacing = 0.5
  dots_center = true
  outer_color = $accent
  inner_color = $base
  font_color = $sky
  fade_on_empty = false
  placeholder_text = <span foreground="##$textAlpha"><i>󰌾 Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>
  hide_input = false
  check_color = $accent
  fail_color = $red
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $peach
  position = 0, 500
  halign = center
  valign = bottom
}
