general {
  # lock_cmd = pidof hyprlock || hyprlock
}

listener {
  # timeout = 1800
  # on-timeout = loginctl lock-session
  # ignore_inhibit = true
}

listener {
  timeout = 600
  on-timeout = hyprctl dispatch "hl.dsp.dpms({ action = 'disable' })"
  # on-resume = hyprctl dispatch dpms on & agsreload & eqcheck
  # on-resume = hyprctl dispatch dpms on & eqcheck & wbreload
  on-resume = hyprctl dispatch "hl.dsp.dpms({ action = 'enable' })"
  # TODO: find what's actually inhibiting sleep rather than just ignoring it
  ignore_inhibit = true
}
