theme {
    style = Fusion
    color_scheme = /home/metin/.local/share/color-schemes/CatppuccinMochaMauve.colors
    icon_theme = Papirus-Dark
    font_fixed = MonoLisa
}

misc {
    menus_have_icons = true
    shortcuts_for_context_menus = true
}
