hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("systemctl --user import-environment --systemd --all")
    hl.exec_cmd("easyeffects --gapplication-service")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'")
    hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("wl-clip-persist --clipboard regular")
    hl.exec_cmd("1password --silent")
    hl.exec_cmd("thunar --daemon")
    hl.exec_cmd("wlsunset -l -33.9 -L 151.2")
    hl.exec_cmd("qs & hyprpaper & swaync & hypridle")
    hl.exec_cmd("[workspace 1 silent] ghostty")
    hl.exec_cmd("[workspace 1 silent] sleep 5; zen-browser")
    hl.exec_cmd("[workspace 7 silent] sleep 10; discord & spotify-launcher")
end)
